language: csharp
mono: none
dotnet: 2.1.502
dist: trusty
sudo: true
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x install-jdk.sh
  - ./install-jdk.sh -F 11 -L BCL
script:
  - dotnet restore
  - cd ./Grammar
  - chmod +x build.sh
  - ./build.sh
  - cd ../Generated
  - dotnet build -c Debug -p:Platform=AnyCPU
  - cd ../Compiler
  - dotnet build -c Debug -p:Platform=AnyCPU
