using System;
using System.Collections.Generic;
using System.Text;

namespace SSLang
{
	/// <summary>
	/// The set of customizable options to control an SSL compilation process.
	/// </summary>
	public sealed class CompilerOptions
	{
		#region Fields
		/// <summary>
		/// The callback for warnings generated by the compiler.
		/// </summary>
		public WarningCallback WarnCallback = null;
		/// <summary>
		/// The callback for verbose messages generated by the compiler.
		/// </summary>
		public VerboseCallback VerboseCallback = null;
		#endregion // Fields
	}

	/// <summary>
	/// Callback for communicating warning messages from the compiler to the client application.
	/// </summary>
	/// <param name="compiler">The compiler that generated the message.</param>
	/// <param name="stage">The compiler stage that generated the message.</param>
	/// <param name="line">The line the warning occured on.</param>
	/// <param name="message">The warning message.</param>
	public delegate void WarningCallback(Compiler compiler, CompilerStage stage, uint line, string message);

	/// <summary>
	/// Callback for communicating verbose information messages from the compiler to the client application.
	/// </summary>
	/// <param name="compiler">The compiler that generated the message.</param>
	/// <param name="stage">The compiler stage that generated the message.</param>
	/// <param name="message">The information message.</param>
	public delegate void VerboseCallback(Compiler compiler, CompilerStage stage, string message);
}
