using Antlr4.Runtime;
using System;
using System.IO;
using System.Linq;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Dfa;
using Antlr4.Runtime.Sharpen;
using SSLang.Generated;

namespace SSLang
{
	internal class ErrorListener : BaseErrorListener, IAntlrErrorListener<int>
	{
		#region Fields
		// The error (if any) generated by the listener
		public CompilerError Error;
		#endregion // Fields

		public override void ReportAmbiguity(Parser recognizer, DFA dfa, int startIndex, int stopIndex, bool exact, BitSet ambigAlts, ATNConfigSet configs)
		{
			base.ReportAmbiguity(recognizer, dfa, startIndex, stopIndex, exact, ambigAlts, configs);
		}

		public override void ReportAttemptingFullContext(Parser recognizer, DFA dfa, int startIndex, int stopIndex, BitSet conflictingAlts, SimulatorState conflictState)
		{
			base.ReportAttemptingFullContext(recognizer, dfa, startIndex, stopIndex, conflictingAlts, conflictState);
		}

		public override void ReportContextSensitivity(Parser recognizer, DFA dfa, int startIndex, int stopIndex, int prediction, SimulatorState acceptState)
		{
			base.ReportContextSensitivity(recognizer, dfa, startIndex, stopIndex, prediction, acceptState);
		}

		public override void SyntaxError(TextWriter output, IRecognizer recognizer, IToken offendingSymbol, int line, int charPositionInLine, string msg, RecognitionException e)
		{
			var ctx = e?.Context;
			var ridx = ctx?.RuleIndex ?? -1;
			var badtxt = offendingSymbol?.Text ?? e.OffendingToken?.Text ?? "";
			string errMsg = null;

			// TODO: Fill this out with better error messages as we find them
			if (ridx == SSL.RULE_file)
				errMsg = $"Unexpected input '{badtxt}' at top level - expected meta statement, variable declaration, or function.";
			else if (ridx == SSL.RULE_versionMetaStatement)
				errMsg = "Invalid shader version statement, ensure it is of the format 'version x.y.z;'.";
			else
			{
				if (msg.Contains("missing ';' at"))
					errMsg = "Unexpected statement - are you missing a semicolon in the preceeding line?";
				else
					errMsg = $"(Rule '{((ridx == -1) ? "none" : SSL.ruleNames[ridx])}') ('{badtxt}') - {msg}";
			}

			var stack = ((SSL)recognizer).GetRuleInvocationStack().ToList();
			stack.Reverse();
			Error = new CompilerError(CompilerStage.Parser, (uint)line, (uint)charPositionInLine, errMsg, stack.ToArray());
		}

		// Called by the lexer
		public void SyntaxError(TextWriter output, IRecognizer recognizer, int offendingSymbol, int line, int charPositionInLine, string msg, RecognitionException e)
		{

		}
	}
}
